name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-all:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: D Compiler Installation
      uses: dlang-community/setup-dlang@v1.1.1
      with:
        compiler: ldc-latest

    - name: Install dependencies
      run: sudo apt-get install -y build-essential gcc g++ ninja-build libgtk-3-dev libplist-dev libimobiledevice-dev

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_D_COMPILER=ldc2

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v3
      with:
        name: provision-full-kit
        path: |
          ${{github.workspace}}/build/anisette_server
          ${{github.workspace}}/build/libprovision.a
          ${{github.workspace}}/build/retrieve_headers
          ${{github.workspace}}/build/sideload_ipa

  build-anisette-server:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: D Compiler Installation
        uses: dlang-community/setup-dlang@v1.1.1
        with:
          compiler: ldc-latest

      - name: Install dependencies
        run: sudo apt-get install -y build-essential gcc g++ ninja-build libplist-dev

      - name: Configure CMake
        run: cmake -G Ninja -Dbuild_sideloadipa=OFF -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_D_COMPILER=ldc2

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
      - uses: actions/upload-artifact@v3
        with:
          name: anisette-server
          path: ${{github.workspace}}/build/anisette_server
