name: ARM builds

on: push

env:
  BUILD_TYPE: Release
  VERBOSE: 1

jobs:
  build-anisette-server-aarch64:
    runs-on: ubuntu-latest
    container: ubuntu:23.04

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y software-properties-common
        add-apt-repository ppa:ubuntu-toolchain-r/ppa
        apt-get install -y git gdc-13-aarch64-linux-gnu dub libz-dev elfutils

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: dub build :anisette-server -b release --compiler=aarch64-linux-gnu-gdc-13 -c "static"

    - name: Rename
      run: mv "bin/provision_anisette-server" "bin/anisette-server-aarch64"

    - name: Put debug symbols in a separate file
      run: eu-strip --strip-debug -f "bin/anisette-server-aarch64.dbg" "bin/anisette-server-aarch64"

    - uses: actions/upload-artifact@v3
      with:
        name: anisette-server-aarch64
        path: |
          bin/anisette-server-aarch64
          bin/anisette-server-aarch64.dbg

  build-anisette-server-armv7:
    runs-on: ubuntu-latest
    container: ubuntu:23.04

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y software-properties-common
        add-apt-repository ppa:ubuntu-toolchain-r/ppa
        apt-get install -y git gdc-13-arm-linux-gnueabihf dub libz-dev elfutils

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: dub build :anisette-server -b release --compiler=arm-linux-gnueabihf-gdc-13 -c "static"

    - name: Rename
      run: mv "bin/provision_anisette-server" "bin/anisette-server-armv7"

    - name: Put debug symbols in a separate file
      run: eu-strip --strip-debug -f "bin/anisette-server-armv7.dbg" "bin/anisette-server-armv7"

    - uses: actions/upload-artifact@v3
      with:
        name: anisette-server-armv7
        path: |
          bin/anisette-server-armv7
          bin/anisette-server-armv7.dbg
